### PR TITLE
Add prettier to format files

### PR DESCRIPTION
**Pull request by maxammann**

### CODE REVIEW

**Comment by maxammann** [comment]
@ahpaleus do you think we need or want something like this?

**Comment by ahpaleus** [comment]
It's ok but not a high priority

**Comment by mschwager** [comment]
If we're going to add `prettier` for Markdown formatting, then IMO we should remove other markdown formatting tools like `markdownlint`. Having two automated formatting tools yelling at each other in CI doesn't seem like the best use of our time.

**Comment by mschwager** [comment]
Closing this for now - let's revisit in the future if we have a need for `prettier`.

**Pull request closed without merging**
